[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "tg-ws-proxy-mac"
dynamic = ["version"]
description = "Local Telegram Desktop WebSocket proxy for macOS"
readme = "docs/README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [{ name = "Flowseal" }, { name = "Konukhov Yaroslav" }]
keywords = ["telegram", "macos", "proxy", "websocket", "mtproto"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: MacOS X",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
    "Topic :: System :: Networking",
]
dependencies = [
    "cryptography==46.0.5",
    "pyobjc-framework-Cocoa==12.2.2",
]

[project.optional-dependencies]
build = ["pyinstaller==6.22.3"]

[project.scripts]
tg-ws-proxy = "proxy.tg_ws_proxy:main"
tg-ws-proxy-tray-macos = "macos:main"

[project.urls]
Source = "https://github.com/f4rceful/tg-ws-proxy-mac"

[tool.hatch.build.targets.wheel]
packages = ["proxy", "utils"]

[tool.hatch.build.force-include]
"macos.py" = "macos.py"
"native_ui.py" = "native_ui.py"

[tool.hatch.version]
path = "proxy/__init__.py"

[tool.ruff.lint]
ignore = ["F403", "F405"]
